import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/state/StoreProvider";
import AuthProvider from "@/context/AuthProvider";
import TanStackQueryProvider from "@/query/TanStackQueryProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <TanStackQueryProvider>
        <html lang="en">
          <body
            className={`antialiased`}
          >
            <AuthProvider>
              {children}
            </AuthProvider>
          </body>
        </html>
      </TanStackQueryProvider>
    </StoreProvider>
  );
}
