import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/providers/StoreProvider";
import AuthProvider from "@/providers/AuthProvider";
import TanStackQueryProvider from "@/providers/TanStackQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"], // you can add "latin-ext" if needed
  display: "swap", // recommended for performance
  variable: "--font-inter", // optional: allows usage in Tailwind
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <TanStackQueryProvider>
        <html lang="en">
          <body className={`${inter.className} antialiased`}>
            <AuthProvider>{children}</AuthProvider>
          </body>
        </html>
      </TanStackQueryProvider>
    </StoreProvider>
  );
}
